# Generated by Django 2.2.1 on 2019-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=100)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
